import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { SidebarProvider } from "@/components/ui/sidebar";
import { SidebarInbox } from "@/components/layout/SidebarInbox";
import { HeaderFilters } from "@/components/layout/HeaderFilters";
import { ThemeProvider } from "@/provider/ThemeProvider";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="h-screen w-screen">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen w-screen`}
			>
				<SidebarProvider>
					<ThemeProvider>
						<main className="flex-1 h-full flex flex-col min-h-0">
							<SidebarInbox />
							<div className="flex-1 flex flex-col min-h-0">
								<HeaderFilters />
								{children}
							</div>
						</main>
					</ThemeProvider>
				</SidebarProvider>
			</body>
		</html>
	);
}
