// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/layout/AppSidebar";
import { SidebarInbox } from "@/components/layout/SidebarInbox";
import { HeaderFilters } from "@/components/layout/HeaderFilters";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{/* SidebarProvider agora engloba toda a estrutura */}
				<SidebarProvider>
					{/* Sidebar fixa */}
					<AppSidebar />

					<main className="w-full flex flex-col">
						{/* Inbox com trigger funcionando */}
						<SidebarInbox />

						{/* Container que agrupa Header + conteúdo */}
						<div className="flex flex-col w-full">
							<HeaderFilters />
							{children}
						</div>
					</main>
				</SidebarProvider>
			</body>
		</html>
	);
}
